### ISSUE TITLE
IDA 7.3 - AttributeError: 'module' object has no attribute 'MAXSTR'

### ISSUE THREAD

**Issue by enzok** [danielplohmann/apiscout#14]
When selecting Filter button the following error is generated.

`
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "C:\Program Files\IDA Pro 7.3\python\ida_kernwin.py", line 6205, in helper_cb
    r = self.handler(button_code)
  File "C:/Users/ez/Desktop/tools/apiscout-master\apiscout\IdaForm.py", line 192, in OnButtonApplyFilter
    self.SetControlValue(self.cApiInfo, "APIs: %d/%d (filtered to 0x%x - 0x%x, range: 0x%x)" % (len(self.apiChooser.items), len(self.apiChooser.all_items), addr_from, addr_to, byte_range))
  File "C:\Program Files\IDA Pro 7.3\python\ida_kernwin.py", line 6924, in SetControlValue
    tid, _ = self.ControlToFieldTypeIdAndSize(ctrl)
  File "C:\Program Files\IDA Pro 7.3\python\ida_kernwin.py", line 6951, in ControlToFieldTypeIdAndSize
    return (3, min(_ida_kernwin.MAXSTR, ctrl.size))
AttributeError: 'module' object has no attribute 'MAXSTR'
`

**Comment by danielplohmann** [comment]
fixed! thanks for pointing this out!
